//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LOJAModel", "FK_VENDA_CLIENTE", "CLIENTE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LojaVirtual.DAO.CLIENTE), "VENDA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LojaVirtual.DAO.VENDA), true)]
[assembly: EdmRelationshipAttribute("LOJAModel", "FK_COMENTARIO_PRODUTO", "PRODUTO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LojaVirtual.DAO.PRODUTO), "COMENTARIO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LojaVirtual.DAO.COMENTARIO), true)]
[assembly: EdmRelationshipAttribute("LOJAModel", "FK_ITEM_VENDA_PRODUTO", "PRODUTO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LojaVirtual.DAO.PRODUTO), "ITEM_VENDA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LojaVirtual.DAO.ITEM_VENDA), true)]
[assembly: EdmRelationshipAttribute("LOJAModel", "FK_ITEM_VENDA_VENDA", "VENDA", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LojaVirtual.DAO.VENDA), "ITEM_VENDA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LojaVirtual.DAO.ITEM_VENDA), true)]
[assembly: EdmRelationshipAttribute("LOJAModel", "FK_VENDA_TIPO_VENDA", "TIPO_VENDA", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LojaVirtual.DAO.TIPO_VENDA), "VENDA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LojaVirtual.DAO.VENDA), true)]

#endregion

namespace LojaVirtual.DAO
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LOJAEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LOJAEntities object using the connection string found in the 'LOJAEntities' section of the application configuration file.
        /// </summary>
        public LOJAEntities() : base("name=LOJAEntities", "LOJAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LOJAEntities object.
        /// </summary>
        public LOJAEntities(string connectionString) : base(connectionString, "LOJAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LOJAEntities object.
        /// </summary>
        public LOJAEntities(EntityConnection connection) : base(connection, "LOJAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BANNER> BANNER
        {
            get
            {
                if ((_BANNER == null))
                {
                    _BANNER = base.CreateObjectSet<BANNER>("BANNER");
                }
                return _BANNER;
            }
        }
        private ObjectSet<BANNER> _BANNER;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CLIENTE> CLIENTE
        {
            get
            {
                if ((_CLIENTE == null))
                {
                    _CLIENTE = base.CreateObjectSet<CLIENTE>("CLIENTE");
                }
                return _CLIENTE;
            }
        }
        private ObjectSet<CLIENTE> _CLIENTE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<COMENTARIO> COMENTARIO
        {
            get
            {
                if ((_COMENTARIO == null))
                {
                    _COMENTARIO = base.CreateObjectSet<COMENTARIO>("COMENTARIO");
                }
                return _COMENTARIO;
            }
        }
        private ObjectSet<COMENTARIO> _COMENTARIO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ITEM_VENDA> ITEM_VENDA
        {
            get
            {
                if ((_ITEM_VENDA == null))
                {
                    _ITEM_VENDA = base.CreateObjectSet<ITEM_VENDA>("ITEM_VENDA");
                }
                return _ITEM_VENDA;
            }
        }
        private ObjectSet<ITEM_VENDA> _ITEM_VENDA;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PRODUTO> PRODUTO
        {
            get
            {
                if ((_PRODUTO == null))
                {
                    _PRODUTO = base.CreateObjectSet<PRODUTO>("PRODUTO");
                }
                return _PRODUTO;
            }
        }
        private ObjectSet<PRODUTO> _PRODUTO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TIPO_VENDA> TIPO_VENDA
        {
            get
            {
                if ((_TIPO_VENDA == null))
                {
                    _TIPO_VENDA = base.CreateObjectSet<TIPO_VENDA>("TIPO_VENDA");
                }
                return _TIPO_VENDA;
            }
        }
        private ObjectSet<TIPO_VENDA> _TIPO_VENDA;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VENDA> VENDA
        {
            get
            {
                if ((_VENDA == null))
                {
                    _VENDA = base.CreateObjectSet<VENDA>("VENDA");
                }
                return _VENDA;
            }
        }
        private ObjectSet<VENDA> _VENDA;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BANNER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBANNER(BANNER bANNER)
        {
            base.AddObject("BANNER", bANNER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CLIENTE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCLIENTE(CLIENTE cLIENTE)
        {
            base.AddObject("CLIENTE", cLIENTE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the COMENTARIO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCOMENTARIO(COMENTARIO cOMENTARIO)
        {
            base.AddObject("COMENTARIO", cOMENTARIO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ITEM_VENDA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToITEM_VENDA(ITEM_VENDA iTEM_VENDA)
        {
            base.AddObject("ITEM_VENDA", iTEM_VENDA);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PRODUTO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPRODUTO(PRODUTO pRODUTO)
        {
            base.AddObject("PRODUTO", pRODUTO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TIPO_VENDA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTIPO_VENDA(TIPO_VENDA tIPO_VENDA)
        {
            base.AddObject("TIPO_VENDA", tIPO_VENDA);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VENDA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVENDA(VENDA vENDA)
        {
            base.AddObject("VENDA", vENDA);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LOJAModel", Name="BANNER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BANNER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BANNER object.
        /// </summary>
        /// <param name="iDT_BANNER">Initial value of the IDT_BANNER property.</param>
        /// <param name="dESCRICAO">Initial value of the DESCRICAO property.</param>
        /// <param name="iMAGEM">Initial value of the IMAGEM property.</param>
        /// <param name="pRIORIDADE">Initial value of the PRIORIDADE property.</param>
        public static BANNER CreateBANNER(global::System.Int32 iDT_BANNER, global::System.String dESCRICAO, global::System.String iMAGEM, global::System.String pRIORIDADE)
        {
            BANNER bANNER = new BANNER();
            bANNER.IDT_BANNER = iDT_BANNER;
            bANNER.DESCRICAO = dESCRICAO;
            bANNER.IMAGEM = iMAGEM;
            bANNER.PRIORIDADE = pRIORIDADE;
            return bANNER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_BANNER
        {
            get
            {
                return _IDT_BANNER;
            }
            set
            {
                if (_IDT_BANNER != value)
                {
                    OnIDT_BANNERChanging(value);
                    ReportPropertyChanging("IDT_BANNER");
                    _IDT_BANNER = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDT_BANNER");
                    OnIDT_BANNERChanged();
                }
            }
        }
        private global::System.Int32 _IDT_BANNER;
        partial void OnIDT_BANNERChanging(global::System.Int32 value);
        partial void OnIDT_BANNERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DESCRICAO
        {
            get
            {
                return _DESCRICAO;
            }
            set
            {
                OnDESCRICAOChanging(value);
                ReportPropertyChanging("DESCRICAO");
                _DESCRICAO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DESCRICAO");
                OnDESCRICAOChanged();
            }
        }
        private global::System.String _DESCRICAO;
        partial void OnDESCRICAOChanging(global::System.String value);
        partial void OnDESCRICAOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IMAGEM
        {
            get
            {
                return _IMAGEM;
            }
            set
            {
                OnIMAGEMChanging(value);
                ReportPropertyChanging("IMAGEM");
                _IMAGEM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IMAGEM");
                OnIMAGEMChanged();
            }
        }
        private global::System.String _IMAGEM;
        partial void OnIMAGEMChanging(global::System.String value);
        partial void OnIMAGEMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PRIORIDADE
        {
            get
            {
                return _PRIORIDADE;
            }
            set
            {
                OnPRIORIDADEChanging(value);
                ReportPropertyChanging("PRIORIDADE");
                _PRIORIDADE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PRIORIDADE");
                OnPRIORIDADEChanged();
            }
        }
        private global::System.String _PRIORIDADE;
        partial void OnPRIORIDADEChanging(global::System.String value);
        partial void OnPRIORIDADEChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LOJAModel", Name="CLIENTE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CLIENTE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CLIENTE object.
        /// </summary>
        /// <param name="iDT_CLIENTE">Initial value of the IDT_CLIENTE property.</param>
        /// <param name="nOME">Initial value of the NOME property.</param>
        /// <param name="eMAIL">Initial value of the EMAIL property.</param>
        /// <param name="sENHA">Initial value of the SENHA property.</param>
        public static CLIENTE CreateCLIENTE(global::System.Int32 iDT_CLIENTE, global::System.String nOME, global::System.String eMAIL, global::System.String sENHA)
        {
            CLIENTE cLIENTE = new CLIENTE();
            cLIENTE.IDT_CLIENTE = iDT_CLIENTE;
            cLIENTE.NOME = nOME;
            cLIENTE.EMAIL = eMAIL;
            cLIENTE.SENHA = sENHA;
            return cLIENTE;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_CLIENTE
        {
            get
            {
                return _IDT_CLIENTE;
            }
            set
            {
                if (_IDT_CLIENTE != value)
                {
                    OnIDT_CLIENTEChanging(value);
                    ReportPropertyChanging("IDT_CLIENTE");
                    _IDT_CLIENTE = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDT_CLIENTE");
                    OnIDT_CLIENTEChanged();
                }
            }
        }
        private global::System.Int32 _IDT_CLIENTE;
        partial void OnIDT_CLIENTEChanging(global::System.Int32 value);
        partial void OnIDT_CLIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOME
        {
            get
            {
                return _NOME;
            }
            set
            {
                OnNOMEChanging(value);
                ReportPropertyChanging("NOME");
                _NOME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOME");
                OnNOMEChanged();
            }
        }
        private global::System.String _NOME;
        partial void OnNOMEChanging(global::System.String value);
        partial void OnNOMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SENHA
        {
            get
            {
                return _SENHA;
            }
            set
            {
                OnSENHAChanging(value);
                ReportPropertyChanging("SENHA");
                _SENHA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SENHA");
                OnSENHAChanged();
            }
        }
        private global::System.String _SENHA;
        partial void OnSENHAChanging(global::System.String value);
        partial void OnSENHAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ENDERECO
        {
            get
            {
                return _ENDERECO;
            }
            set
            {
                OnENDERECOChanging(value);
                ReportPropertyChanging("ENDERECO");
                _ENDERECO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ENDERECO");
                OnENDERECOChanged();
            }
        }
        private global::System.String _ENDERECO;
        partial void OnENDERECOChanging(global::System.String value);
        partial void OnENDERECOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJAModel", "FK_VENDA_CLIENTE", "VENDA")]
        public EntityCollection<VENDA> VENDA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VENDA>("LOJAModel.FK_VENDA_CLIENTE", "VENDA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VENDA>("LOJAModel.FK_VENDA_CLIENTE", "VENDA", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LOJAModel", Name="COMENTARIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class COMENTARIO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new COMENTARIO object.
        /// </summary>
        /// <param name="iDT_COMENTARIO">Initial value of the IDT_COMENTARIO property.</param>
        /// <param name="nOME">Initial value of the NOME property.</param>
        /// <param name="eMAIL">Initial value of the EMAIL property.</param>
        /// <param name="iDT_PRODUTO">Initial value of the IDT_PRODUTO property.</param>
        /// <param name="nOTA">Initial value of the NOTA property.</param>
        public static COMENTARIO CreateCOMENTARIO(global::System.Int32 iDT_COMENTARIO, global::System.String nOME, global::System.String eMAIL, global::System.Int32 iDT_PRODUTO, global::System.Int32 nOTA)
        {
            COMENTARIO cOMENTARIO = new COMENTARIO();
            cOMENTARIO.IDT_COMENTARIO = iDT_COMENTARIO;
            cOMENTARIO.NOME = nOME;
            cOMENTARIO.EMAIL = eMAIL;
            cOMENTARIO.IDT_PRODUTO = iDT_PRODUTO;
            cOMENTARIO.NOTA = nOTA;
            return cOMENTARIO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_COMENTARIO
        {
            get
            {
                return _IDT_COMENTARIO;
            }
            set
            {
                if (_IDT_COMENTARIO != value)
                {
                    OnIDT_COMENTARIOChanging(value);
                    ReportPropertyChanging("IDT_COMENTARIO");
                    _IDT_COMENTARIO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDT_COMENTARIO");
                    OnIDT_COMENTARIOChanged();
                }
            }
        }
        private global::System.Int32 _IDT_COMENTARIO;
        partial void OnIDT_COMENTARIOChanging(global::System.Int32 value);
        partial void OnIDT_COMENTARIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOME
        {
            get
            {
                return _NOME;
            }
            set
            {
                OnNOMEChanging(value);
                ReportPropertyChanging("NOME");
                _NOME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOME");
                OnNOMEChanged();
            }
        }
        private global::System.String _NOME;
        partial void OnNOMEChanging(global::System.String value);
        partial void OnNOMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRICAO
        {
            get
            {
                return _DESCRICAO;
            }
            set
            {
                OnDESCRICAOChanging(value);
                ReportPropertyChanging("DESCRICAO");
                _DESCRICAO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRICAO");
                OnDESCRICAOChanged();
            }
        }
        private global::System.String _DESCRICAO;
        partial void OnDESCRICAOChanging(global::System.String value);
        partial void OnDESCRICAOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_PRODUTO
        {
            get
            {
                return _IDT_PRODUTO;
            }
            set
            {
                OnIDT_PRODUTOChanging(value);
                ReportPropertyChanging("IDT_PRODUTO");
                _IDT_PRODUTO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDT_PRODUTO");
                OnIDT_PRODUTOChanged();
            }
        }
        private global::System.Int32 _IDT_PRODUTO;
        partial void OnIDT_PRODUTOChanging(global::System.Int32 value);
        partial void OnIDT_PRODUTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NOTA
        {
            get
            {
                return _NOTA;
            }
            set
            {
                OnNOTAChanging(value);
                ReportPropertyChanging("NOTA");
                _NOTA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NOTA");
                OnNOTAChanged();
            }
        }
        private global::System.Int32 _NOTA;
        partial void OnNOTAChanging(global::System.Int32 value);
        partial void OnNOTAChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJAModel", "FK_COMENTARIO_PRODUTO", "PRODUTO")]
        public PRODUTO PRODUTO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUTO>("LOJAModel.FK_COMENTARIO_PRODUTO", "PRODUTO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUTO>("LOJAModel.FK_COMENTARIO_PRODUTO", "PRODUTO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PRODUTO> PRODUTOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUTO>("LOJAModel.FK_COMENTARIO_PRODUTO", "PRODUTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PRODUTO>("LOJAModel.FK_COMENTARIO_PRODUTO", "PRODUTO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LOJAModel", Name="ITEM_VENDA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ITEM_VENDA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ITEM_VENDA object.
        /// </summary>
        /// <param name="iDT_VENDA">Initial value of the IDT_VENDA property.</param>
        /// <param name="iDT_PRODUTO">Initial value of the IDT_PRODUTO property.</param>
        /// <param name="qUANTIDADE">Initial value of the QUANTIDADE property.</param>
        /// <param name="vALOR_UNITARIO">Initial value of the VALOR_UNITARIO property.</param>
        public static ITEM_VENDA CreateITEM_VENDA(global::System.Int32 iDT_VENDA, global::System.Int32 iDT_PRODUTO, global::System.Int32 qUANTIDADE, global::System.Decimal vALOR_UNITARIO)
        {
            ITEM_VENDA iTEM_VENDA = new ITEM_VENDA();
            iTEM_VENDA.IDT_VENDA = iDT_VENDA;
            iTEM_VENDA.IDT_PRODUTO = iDT_PRODUTO;
            iTEM_VENDA.QUANTIDADE = qUANTIDADE;
            iTEM_VENDA.VALOR_UNITARIO = vALOR_UNITARIO;
            return iTEM_VENDA;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_VENDA
        {
            get
            {
                return _IDT_VENDA;
            }
            set
            {
                if (_IDT_VENDA != value)
                {
                    OnIDT_VENDAChanging(value);
                    ReportPropertyChanging("IDT_VENDA");
                    _IDT_VENDA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDT_VENDA");
                    OnIDT_VENDAChanged();
                }
            }
        }
        private global::System.Int32 _IDT_VENDA;
        partial void OnIDT_VENDAChanging(global::System.Int32 value);
        partial void OnIDT_VENDAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_PRODUTO
        {
            get
            {
                return _IDT_PRODUTO;
            }
            set
            {
                if (_IDT_PRODUTO != value)
                {
                    OnIDT_PRODUTOChanging(value);
                    ReportPropertyChanging("IDT_PRODUTO");
                    _IDT_PRODUTO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDT_PRODUTO");
                    OnIDT_PRODUTOChanged();
                }
            }
        }
        private global::System.Int32 _IDT_PRODUTO;
        partial void OnIDT_PRODUTOChanging(global::System.Int32 value);
        partial void OnIDT_PRODUTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QUANTIDADE
        {
            get
            {
                return _QUANTIDADE;
            }
            set
            {
                OnQUANTIDADEChanging(value);
                ReportPropertyChanging("QUANTIDADE");
                _QUANTIDADE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QUANTIDADE");
                OnQUANTIDADEChanged();
            }
        }
        private global::System.Int32 _QUANTIDADE;
        partial void OnQUANTIDADEChanging(global::System.Int32 value);
        partial void OnQUANTIDADEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal VALOR_UNITARIO
        {
            get
            {
                return _VALOR_UNITARIO;
            }
            set
            {
                OnVALOR_UNITARIOChanging(value);
                ReportPropertyChanging("VALOR_UNITARIO");
                _VALOR_UNITARIO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VALOR_UNITARIO");
                OnVALOR_UNITARIOChanged();
            }
        }
        private global::System.Decimal _VALOR_UNITARIO;
        partial void OnVALOR_UNITARIOChanging(global::System.Decimal value);
        partial void OnVALOR_UNITARIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SUBTOTAL
        {
            get
            {
                return _SUBTOTAL;
            }
            set
            {
                OnSUBTOTALChanging(value);
                ReportPropertyChanging("SUBTOTAL");
                _SUBTOTAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SUBTOTAL");
                OnSUBTOTALChanged();
            }
        }
        private Nullable<global::System.Decimal> _SUBTOTAL;
        partial void OnSUBTOTALChanging(Nullable<global::System.Decimal> value);
        partial void OnSUBTOTALChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJAModel", "FK_ITEM_VENDA_PRODUTO", "PRODUTO")]
        public PRODUTO PRODUTO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUTO>("LOJAModel.FK_ITEM_VENDA_PRODUTO", "PRODUTO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUTO>("LOJAModel.FK_ITEM_VENDA_PRODUTO", "PRODUTO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PRODUTO> PRODUTOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUTO>("LOJAModel.FK_ITEM_VENDA_PRODUTO", "PRODUTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PRODUTO>("LOJAModel.FK_ITEM_VENDA_PRODUTO", "PRODUTO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJAModel", "FK_ITEM_VENDA_VENDA", "VENDA")]
        public VENDA VENDA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VENDA>("LOJAModel.FK_ITEM_VENDA_VENDA", "VENDA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VENDA>("LOJAModel.FK_ITEM_VENDA_VENDA", "VENDA").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VENDA> VENDAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VENDA>("LOJAModel.FK_ITEM_VENDA_VENDA", "VENDA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VENDA>("LOJAModel.FK_ITEM_VENDA_VENDA", "VENDA", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LOJAModel", Name="PRODUTO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PRODUTO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PRODUTO object.
        /// </summary>
        /// <param name="iDT_PRODUTO">Initial value of the IDT_PRODUTO property.</param>
        /// <param name="nOME">Initial value of the NOME property.</param>
        /// <param name="vALOR">Initial value of the VALOR property.</param>
        public static PRODUTO CreatePRODUTO(global::System.Int32 iDT_PRODUTO, global::System.String nOME, global::System.Decimal vALOR)
        {
            PRODUTO pRODUTO = new PRODUTO();
            pRODUTO.IDT_PRODUTO = iDT_PRODUTO;
            pRODUTO.NOME = nOME;
            pRODUTO.VALOR = vALOR;
            return pRODUTO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_PRODUTO
        {
            get
            {
                return _IDT_PRODUTO;
            }
            set
            {
                if (_IDT_PRODUTO != value)
                {
                    OnIDT_PRODUTOChanging(value);
                    ReportPropertyChanging("IDT_PRODUTO");
                    _IDT_PRODUTO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDT_PRODUTO");
                    OnIDT_PRODUTOChanged();
                }
            }
        }
        private global::System.Int32 _IDT_PRODUTO;
        partial void OnIDT_PRODUTOChanging(global::System.Int32 value);
        partial void OnIDT_PRODUTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOME
        {
            get
            {
                return _NOME;
            }
            set
            {
                OnNOMEChanging(value);
                ReportPropertyChanging("NOME");
                _NOME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOME");
                OnNOMEChanged();
            }
        }
        private global::System.String _NOME;
        partial void OnNOMEChanging(global::System.String value);
        partial void OnNOMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRICAO
        {
            get
            {
                return _DESCRICAO;
            }
            set
            {
                OnDESCRICAOChanging(value);
                ReportPropertyChanging("DESCRICAO");
                _DESCRICAO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRICAO");
                OnDESCRICAOChanged();
            }
        }
        private global::System.String _DESCRICAO;
        partial void OnDESCRICAOChanging(global::System.String value);
        partial void OnDESCRICAOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal VALOR
        {
            get
            {
                return _VALOR;
            }
            set
            {
                OnVALORChanging(value);
                ReportPropertyChanging("VALOR");
                _VALOR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VALOR");
                OnVALORChanged();
            }
        }
        private global::System.Decimal _VALOR;
        partial void OnVALORChanging(global::System.Decimal value);
        partial void OnVALORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FOTO
        {
            get
            {
                return _FOTO;
            }
            set
            {
                OnFOTOChanging(value);
                ReportPropertyChanging("FOTO");
                _FOTO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FOTO");
                OnFOTOChanged();
            }
        }
        private global::System.String _FOTO;
        partial void OnFOTOChanging(global::System.String value);
        partial void OnFOTOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJAModel", "FK_COMENTARIO_PRODUTO", "COMENTARIO")]
        public EntityCollection<COMENTARIO> COMENTARIO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<COMENTARIO>("LOJAModel.FK_COMENTARIO_PRODUTO", "COMENTARIO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<COMENTARIO>("LOJAModel.FK_COMENTARIO_PRODUTO", "COMENTARIO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJAModel", "FK_ITEM_VENDA_PRODUTO", "ITEM_VENDA")]
        public EntityCollection<ITEM_VENDA> ITEM_VENDA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ITEM_VENDA>("LOJAModel.FK_ITEM_VENDA_PRODUTO", "ITEM_VENDA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ITEM_VENDA>("LOJAModel.FK_ITEM_VENDA_PRODUTO", "ITEM_VENDA", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LOJAModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LOJAModel", Name="TIPO_VENDA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TIPO_VENDA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TIPO_VENDA object.
        /// </summary>
        /// <param name="iDT_TIPO_VENDA">Initial value of the IDT_TIPO_VENDA property.</param>
        public static TIPO_VENDA CreateTIPO_VENDA(global::System.Int32 iDT_TIPO_VENDA)
        {
            TIPO_VENDA tIPO_VENDA = new TIPO_VENDA();
            tIPO_VENDA.IDT_TIPO_VENDA = iDT_TIPO_VENDA;
            return tIPO_VENDA;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_TIPO_VENDA
        {
            get
            {
                return _IDT_TIPO_VENDA;
            }
            set
            {
                if (_IDT_TIPO_VENDA != value)
                {
                    OnIDT_TIPO_VENDAChanging(value);
                    ReportPropertyChanging("IDT_TIPO_VENDA");
                    _IDT_TIPO_VENDA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDT_TIPO_VENDA");
                    OnIDT_TIPO_VENDAChanged();
                }
            }
        }
        private global::System.Int32 _IDT_TIPO_VENDA;
        partial void OnIDT_TIPO_VENDAChanging(global::System.Int32 value);
        partial void OnIDT_TIPO_VENDAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRICAO
        {
            get
            {
                return _DESCRICAO;
            }
            set
            {
                OnDESCRICAOChanging(value);
                ReportPropertyChanging("DESCRICAO");
                _DESCRICAO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRICAO");
                OnDESCRICAOChanged();
            }
        }
        private global::System.String _DESCRICAO;
        partial void OnDESCRICAOChanging(global::System.String value);
        partial void OnDESCRICAOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJAModel", "FK_VENDA_TIPO_VENDA", "VENDA")]
        public EntityCollection<VENDA> VENDA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VENDA>("LOJAModel.FK_VENDA_TIPO_VENDA", "VENDA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VENDA>("LOJAModel.FK_VENDA_TIPO_VENDA", "VENDA", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LOJAModel", Name="VENDA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VENDA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VENDA object.
        /// </summary>
        /// <param name="iDT_VENDA">Initial value of the IDT_VENDA property.</param>
        /// <param name="iDT_CLIENTE">Initial value of the IDT_CLIENTE property.</param>
        /// <param name="iDT_TIPO_VENDA">Initial value of the IDT_TIPO_VENDA property.</param>
        /// <param name="vALOR_TOTAL">Initial value of the VALOR_TOTAL property.</param>
        public static VENDA CreateVENDA(global::System.Int32 iDT_VENDA, global::System.Int32 iDT_CLIENTE, global::System.Int32 iDT_TIPO_VENDA, global::System.Decimal vALOR_TOTAL)
        {
            VENDA vENDA = new VENDA();
            vENDA.IDT_VENDA = iDT_VENDA;
            vENDA.IDT_CLIENTE = iDT_CLIENTE;
            vENDA.IDT_TIPO_VENDA = iDT_TIPO_VENDA;
            vENDA.VALOR_TOTAL = vALOR_TOTAL;
            return vENDA;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_VENDA
        {
            get
            {
                return _IDT_VENDA;
            }
            set
            {
                if (_IDT_VENDA != value)
                {
                    OnIDT_VENDAChanging(value);
                    ReportPropertyChanging("IDT_VENDA");
                    _IDT_VENDA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDT_VENDA");
                    OnIDT_VENDAChanged();
                }
            }
        }
        private global::System.Int32 _IDT_VENDA;
        partial void OnIDT_VENDAChanging(global::System.Int32 value);
        partial void OnIDT_VENDAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_CLIENTE
        {
            get
            {
                return _IDT_CLIENTE;
            }
            set
            {
                OnIDT_CLIENTEChanging(value);
                ReportPropertyChanging("IDT_CLIENTE");
                _IDT_CLIENTE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDT_CLIENTE");
                OnIDT_CLIENTEChanged();
            }
        }
        private global::System.Int32 _IDT_CLIENTE;
        partial void OnIDT_CLIENTEChanging(global::System.Int32 value);
        partial void OnIDT_CLIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_TIPO_VENDA
        {
            get
            {
                return _IDT_TIPO_VENDA;
            }
            set
            {
                OnIDT_TIPO_VENDAChanging(value);
                ReportPropertyChanging("IDT_TIPO_VENDA");
                _IDT_TIPO_VENDA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDT_TIPO_VENDA");
                OnIDT_TIPO_VENDAChanged();
            }
        }
        private global::System.Int32 _IDT_TIPO_VENDA;
        partial void OnIDT_TIPO_VENDAChanging(global::System.Int32 value);
        partial void OnIDT_TIPO_VENDAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal VALOR_TOTAL
        {
            get
            {
                return _VALOR_TOTAL;
            }
            set
            {
                OnVALOR_TOTALChanging(value);
                ReportPropertyChanging("VALOR_TOTAL");
                _VALOR_TOTAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VALOR_TOTAL");
                OnVALOR_TOTALChanged();
            }
        }
        private global::System.Decimal _VALOR_TOTAL;
        partial void OnVALOR_TOTALChanging(global::System.Decimal value);
        partial void OnVALOR_TOTALChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJAModel", "FK_VENDA_CLIENTE", "CLIENTE")]
        public CLIENTE CLIENTE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENTE>("LOJAModel.FK_VENDA_CLIENTE", "CLIENTE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENTE>("LOJAModel.FK_VENDA_CLIENTE", "CLIENTE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CLIENTE> CLIENTEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENTE>("LOJAModel.FK_VENDA_CLIENTE", "CLIENTE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CLIENTE>("LOJAModel.FK_VENDA_CLIENTE", "CLIENTE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJAModel", "FK_ITEM_VENDA_VENDA", "ITEM_VENDA")]
        public EntityCollection<ITEM_VENDA> ITEM_VENDA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ITEM_VENDA>("LOJAModel.FK_ITEM_VENDA_VENDA", "ITEM_VENDA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ITEM_VENDA>("LOJAModel.FK_ITEM_VENDA_VENDA", "ITEM_VENDA", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJAModel", "FK_VENDA_TIPO_VENDA", "TIPO_VENDA")]
        public TIPO_VENDA TIPO_VENDA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TIPO_VENDA>("LOJAModel.FK_VENDA_TIPO_VENDA", "TIPO_VENDA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TIPO_VENDA>("LOJAModel.FK_VENDA_TIPO_VENDA", "TIPO_VENDA").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TIPO_VENDA> TIPO_VENDAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TIPO_VENDA>("LOJAModel.FK_VENDA_TIPO_VENDA", "TIPO_VENDA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TIPO_VENDA>("LOJAModel.FK_VENDA_TIPO_VENDA", "TIPO_VENDA", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
